services:
  auth-database:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=auth-db'
      - 'POSTGRES_PASSWORD=auth'
      - 'POSTGRES_USER=auth'
    ports:
      - "5432:5432"
    expose:
      - "5432"
    command: -p 5432
  auth-liquibase:
    image: liquibase/liquibase
    container_name: auth_migrations
    depends_on:
      - auth-database
    volumes:
      - ./auth-migrations:/changesets
    command:
      - --searchPath=/changesets
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://auth-database:5432/auth-db
      - --username=auth
      - --password=auth
      - update
