name: Publish Docker image

on:
  pull_request:
    branches: [ "master"]
  push:
    branches:
      - docker-upload

jobs:
  upload-AuthService:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean package -f AuthService

      - name: Build Docker Image
        run: |
                    cd ./AuthService
                    docker build -t authservice:latest .
                    cd ../

      - name: Push Docker Image
        run: |
          cd ./AuthService
          docker tag authservice:latest ${{ secrets.DOCKER_USERNAME }}/authservice:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/authservice:latest   
          cd ../
          
  upload-ChatSettingsService:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean package -f ChatSettingsService

      - name: Build Docker Image
        run: |
                    cd ./ChatSettingsService
                    docker build -t chat-setting-service:latest .
                    cd ../

      - name: Push Docker Image
        run: |
          cd ./ChatSettingsService
          docker tag chat-setting-service:latest ${{ secrets.DOCKER_USERNAME }}/chat-setting-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/chat-setting-service:latest   
          cd ../

  upload-HistoryService:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean package -f HistoryService

      - name: Build Docker Image
        run: |
                    cd ./HistoryService
                    docker build -t chat-history-service:latest .
                    cd ../

      - name: Push Docker Image
        run: |
          cd ./HistoryService
          docker tag chat-history-service:latest ${{ secrets.DOCKER_USERNAME }}/chat-history-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/chat-history-service:latest
          cd ../
          
  upload-MessageRecievingService:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean package -f MessageRecievingService

      - name: Build Docker Image
        run: |
                    cd ./MessageRecievingService
                    docker build -t message-receiving-service:latest .
                    cd ../

      - name: Push Docker Image
        run: |
          cd ./MessageRecievingService
          docker tag message-receiving-service:latest ${{ secrets.DOCKER_USERNAME }}/message-receiving-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/message-receiving-service:latest
          cd ../
  upload-MessageSendingService:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean package -f MessageSendingService

      - name: Build Docker Image
        run: |
                    cd ./MessageSendingService
                    docker build -t message-sending-service:latest .
                    cd ../

      - name: Push Docker Image
        run: |
          cd ./MessageSendingService
          docker tag message-sending-service:latest ${{ secrets.DOCKER_USERNAME }}/message-sending-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/message-sending-service:latest 
          cd ../
