name: Publish Docker image

on:
  push:
    branches: [ "docker-upload"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean package -f AuthService

      - name: Build Docker Image
        run: |
                    docker build -t AuthService:latest .

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          target: final
          tags: ${{ vars.DOCKER_USERNAME }}/AuthService:latest
